create extension if not exists pg_cron with schema pg_catalog;

create table public.crawl_runs (
	id bigint generated by default as identity primary key,
	source text not null,
	lock_token uuid not null unique,
	status text not null default 'running',
	started_at timestamp with time zone not null default now(),
	stale_after timestamp with time zone not null,
	finished_at timestamp with time zone,
	duration_ms bigint,
	retry_count integer not null default 0,
	attempted_count integer not null default 0,
	succeeded_count integer not null default 0,
	extracted_count integer not null default 0,
	inserted_count integer not null default 0,
	skipped_count integer not null default 0,
	warning_count integer not null default 0,
	failure_count integer not null default 0,
	network_failure_count integer not null default 0,
	parser_failure_count integer not null default 0,
	timeout_failure_count integer not null default 0,
	parser_valid_count integer not null default 0,
	parser_minimum_count integer not null default 0,
	warnings jsonb not null default '[]'::jsonb,
	failures jsonb not null default '[]'::jsonb,
	parser_observations jsonb not null default '[]'::jsonb,
	error_stage text,
	error_message text,
	constraint crawl_runs_source_check
		check (source in ('arcalive', 'battlepage', 'insagirl', 'issuelink')),
	constraint crawl_runs_status_check
		check (status in ('running', 'succeeded', 'partial', 'failed', 'interrupted')),
	constraint crawl_runs_time_check
		check (
			(status = 'running' and finished_at is null and duration_ms is null)
			or (status <> 'running' and finished_at is not null and duration_ms is not null)
		),
	constraint crawl_runs_duration_check check (duration_ms is null or duration_ms >= 0),
	constraint crawl_runs_counts_check check (
		retry_count >= 0
		and attempted_count >= 0
		and succeeded_count >= 0
		and succeeded_count <= attempted_count
		and extracted_count >= 0
		and inserted_count >= 0
		and skipped_count >= 0
		and warning_count >= 0
		and failure_count >= 0
		and network_failure_count >= 0
		and parser_failure_count >= 0
		and timeout_failure_count >= 0
		and parser_valid_count >= 0
		and parser_minimum_count >= 0
	),
	constraint crawl_runs_failure_counts_check check (
		failure_count = network_failure_count + parser_failure_count + timeout_failure_count
	),
	constraint crawl_runs_json_arrays_check check (
		jsonb_typeof(warnings) = 'array'
		and jsonb_typeof(failures) = 'array'
		and jsonb_typeof(parser_observations) = 'array'
	),
	constraint crawl_runs_error_stage_check check (
		error_stage is null
		or error_stage in ('source', 'filter', 'history', 'ingest', 'unknown')
	)
);

create index crawl_runs_started_at_id_idx
	on public.crawl_runs (started_at desc, id desc);
create index crawl_runs_source_started_at_idx
	on public.crawl_runs (source, started_at desc, id desc);
create index crawl_runs_running_idx
	on public.crawl_runs (stale_after)
	where status = 'running';

alter table public.crawl_runs enable row level security;

revoke all on table public.crawl_runs from public, anon, authenticated;
revoke all on sequence public.crawl_runs_id_seq from public, anon, authenticated;
grant all on table public.crawl_runs to service_role;
grant all on sequence public.crawl_runs_id_seq to service_role;

create or replace function public.begin_crawl_run(
	p_source text,
	p_lock_token uuid,
	p_ttl_seconds integer default 300
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_acquired boolean;
	v_run_id bigint;
	v_active_run_id bigint;
begin
	if p_source not in ('arcalive', 'battlepage', 'insagirl', 'issuelink') then
		raise exception using errcode = '22023', message = 'Unsupported crawl source.';
	end if;

	if p_lock_token is null then
		raise exception using errcode = '22023', message = 'A crawl lock token is required.';
	end if;

	if p_ttl_seconds < 30 or p_ttl_seconds > 900 then
		raise exception using errcode = '22023', message = 'Crawl lock TTL must be between 30 and 900 seconds.';
	end if;

	update public.crawl_runs
	set
		status = 'interrupted',
		finished_at = stale_after,
		duration_ms = greatest(
			0,
			floor(extract(epoch from (stale_after - started_at)) * 1000)::bigint
		),
		error_stage = coalesce(error_stage, 'unknown'),
		error_message = coalesce(error_message, '크롤링 실행이 제한 시간 안에 종료되지 않았습니다.')
	where status = 'running'
		and stale_after <= now();

	insert into public.crawl_run_locks (lock_key, lock_token, locked_until, updated_at)
	values (
		'global-crawl',
		p_lock_token,
		now() + make_interval(secs => p_ttl_seconds),
		now()
	)
	on conflict (lock_key) do update
	set
		lock_token = excluded.lock_token,
		locked_until = excluded.locked_until,
		updated_at = excluded.updated_at
	where public.crawl_run_locks.locked_until <= now()
	returning true into v_acquired;

	if not coalesce(v_acquired, false) then
		select run.id
		into v_active_run_id
		from public.crawl_runs as run
		inner join public.crawl_run_locks as lock
			on lock.lock_key = 'global-crawl'
			and lock.lock_token = run.lock_token
		where run.status = 'running'
		order by run.started_at desc, run.id desc
		limit 1;

		return jsonb_build_object(
			'acquired', false,
			'activeRunId', case when v_active_run_id is null then null else v_active_run_id::text end
		);
	end if;

	insert into public.crawl_runs (source, lock_token, stale_after)
	values (
		p_source,
		p_lock_token,
		now() + make_interval(secs => p_ttl_seconds)
	)
	returning id into v_run_id;

	return jsonb_build_object('acquired', true, 'runId', v_run_id::text);
end;
$$;

create or replace function public.finish_crawl_run(
	p_run_id bigint,
	p_lock_token uuid,
	p_result jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_status text;
	v_warnings jsonb;
	v_failures jsonb;
	v_parser_observations jsonb;
	v_finished_at timestamp with time zone := now();
	v_duration_ms bigint;
begin
	if p_result is null or jsonb_typeof(p_result) <> 'object' then
		raise exception using errcode = '22023', message = 'Crawl run result must be a JSON object.';
	end if;

	v_status := p_result ->> 'status';
	if v_status not in ('succeeded', 'partial', 'failed') then
		raise exception using errcode = '22023', message = 'Unsupported terminal crawl run status.';
	end if;

	v_warnings := coalesce(p_result -> 'warnings', '[]'::jsonb);
	v_failures := coalesce(p_result -> 'failures', '[]'::jsonb);
	v_parser_observations := coalesce(p_result -> 'parserObservations', '[]'::jsonb);
	if jsonb_typeof(v_warnings) <> 'array'
		or jsonb_typeof(v_failures) <> 'array'
		or jsonb_typeof(v_parser_observations) <> 'array'
	then
		raise exception using errcode = '22023', message = 'Crawl run details must be JSON arrays.';
	end if;

	update public.crawl_runs
	set
		status = v_status,
		finished_at = v_finished_at,
		duration_ms = greatest(
			0,
			floor(extract(epoch from (v_finished_at - started_at)) * 1000)::bigint
		),
		retry_count = coalesce((p_result ->> 'retryCount')::integer, 0),
		attempted_count = coalesce((p_result ->> 'attemptedCount')::integer, 0),
		succeeded_count = coalesce((p_result ->> 'succeededCount')::integer, 0),
		extracted_count = coalesce((p_result ->> 'extractedCount')::integer, 0),
		inserted_count = coalesce((p_result ->> 'insertedCount')::integer, 0),
		skipped_count = coalesce((p_result ->> 'skippedCount')::integer, 0),
		warning_count = coalesce((p_result ->> 'warningCount')::integer, 0),
		failure_count = coalesce((p_result ->> 'failureCount')::integer, 0),
		network_failure_count = coalesce((p_result ->> 'networkFailureCount')::integer, 0),
		parser_failure_count = coalesce((p_result ->> 'parserFailureCount')::integer, 0),
		timeout_failure_count = coalesce((p_result ->> 'timeoutFailureCount')::integer, 0),
		parser_valid_count = coalesce((p_result ->> 'parserValidCount')::integer, 0),
		parser_minimum_count = coalesce((p_result ->> 'parserMinimumCount')::integer, 0),
		warnings = v_warnings,
		failures = v_failures,
		parser_observations = v_parser_observations,
		error_stage = nullif(p_result ->> 'errorStage', ''),
		error_message = nullif(p_result ->> 'errorMessage', '')
	where id = p_run_id
		and lock_token = p_lock_token
		and status = 'running'
	returning duration_ms into v_duration_ms;

	if v_duration_ms is null then
		raise exception using errcode = 'P0002', message = 'Running crawl run was not found.';
	end if;

	delete from public.crawl_run_locks
	where lock_key = 'global-crawl'
		and lock_token = p_lock_token;

	return jsonb_build_object(
		'runId', p_run_id::text,
		'status', v_status,
		'durationMs', v_duration_ms
	);
end;
$$;

create or replace function public.get_crawl_runs_dashboard(
	p_limit integer default 20,
	p_trend_limit integer default 20
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
	v_result jsonb;
begin
	if not public.is_applemint_owner() then
		raise exception using
			errcode = '42501',
			message = 'Only the Applemint owner can read crawl run history.';
	end if;

	if p_limit < 1 or p_limit > 50 or p_trend_limit < 1 or p_trend_limit > 50 then
		raise exception using errcode = '22023', message = 'Crawl dashboard limits must be between 1 and 50.';
	end if;

	with effective_runs as materialized (
		select
			run.*,
			case
				when run.status = 'running' and run.stale_after <= now() then 'interrupted'
				else run.status
			end as effective_status,
			case
				when run.status = 'running' and run.stale_after <= now() then run.stale_after
				else run.finished_at
			end as effective_finished_at,
			case
				when run.status = 'running' and run.stale_after <= now() then greatest(
					0,
					floor(extract(epoch from (run.stale_after - run.started_at)) * 1000)::bigint
				)
				else run.duration_ms
			end as effective_duration_ms
		from public.crawl_runs as run
	),
	sources(source) as (
		values ('arcalive'::text), ('battlepage'), ('insagirl'), ('issuelink')
	),
	recent_runs as (
		select *
		from effective_runs
		order by started_at desc, id desc
		limit p_limit
	),
	active_run as (
		select *
		from effective_runs
		where effective_status = 'running'
		order by started_at desc, id desc
		limit 1
	)
	select jsonb_build_object(
		'activeRun', (
			select jsonb_build_object(
				'id', active.id::text,
				'source', active.source,
				'status', active.effective_status,
				'startedAt', active.started_at,
				'staleAfter', active.stale_after
			)
			from active_run as active
		),
		'sources', coalesce((
			select jsonb_agg(
				jsonb_build_object(
					'source', source_row.source,
					'lastSuccessAt', (
						select max(run.effective_finished_at)
						from effective_runs as run
						where run.source = source_row.source
							and run.effective_status in ('succeeded', 'partial')
					),
					'lastFailureAt', (
						select max(run.effective_finished_at)
						from effective_runs as run
						where run.source = source_row.source
							and (
								run.effective_status in ('failed', 'interrupted')
								or run.failure_count > 0
							)
					),
					'latest', (
						select jsonb_build_object(
							'id', run.id::text,
							'status', run.effective_status,
							'startedAt', run.started_at,
							'durationMs', run.effective_duration_ms,
							'extractedCount', run.extracted_count,
							'insertedCount', run.inserted_count
						)
						from effective_runs as run
						where run.source = source_row.source
						order by run.started_at desc, run.id desc
						limit 1
					),
					'trend', coalesce((
						select jsonb_agg(
							jsonb_build_object(
								'id', trend.id::text,
								'status', trend.effective_status,
								'startedAt', trend.started_at,
								'extractedCount', trend.extracted_count,
								'parserValidCount', trend.parser_valid_count,
								'parserMinimumCount', trend.parser_minimum_count,
								'failureCount', trend.failure_count
							)
							order by trend.started_at asc, trend.id asc
						)
						from (
							select *
							from effective_runs as run
							where run.source = source_row.source
								and run.effective_status <> 'running'
							order by run.started_at desc, run.id desc
							limit p_trend_limit
						) as trend
					), '[]'::jsonb)
				)
				order by source_row.source
			)
			from sources as source_row
		), '[]'::jsonb),
		'runs', coalesce((
			select jsonb_agg(
				jsonb_build_object(
					'id', run.id::text,
					'source', run.source,
					'status', run.effective_status,
					'startedAt', run.started_at,
					'finishedAt', run.effective_finished_at,
					'durationMs', run.effective_duration_ms,
					'retryCount', run.retry_count,
					'attemptedCount', run.attempted_count,
					'succeededCount', run.succeeded_count,
					'extractedCount', run.extracted_count,
					'insertedCount', run.inserted_count,
					'skippedCount', run.skipped_count,
					'warningCount', run.warning_count,
					'failureCount', run.failure_count,
					'networkFailureCount', run.network_failure_count,
					'parserFailureCount', run.parser_failure_count,
					'timeoutFailureCount', run.timeout_failure_count,
					'parserValidCount', run.parser_valid_count,
					'parserMinimumCount', run.parser_minimum_count,
					'warnings', run.warnings,
					'failures', run.failures,
					'parserObservations', run.parser_observations,
					'errorStage', run.error_stage,
					'errorMessage', run.error_message
				)
				order by run.started_at desc, run.id desc
			)
			from recent_runs as run
		), '[]'::jsonb)
	)
	into v_result;

	return v_result;
end;
$$;

create or replace function public.cleanup_crawl_runs()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_deleted_count bigint;
begin
	update public.crawl_runs
	set
		status = 'interrupted',
		finished_at = stale_after,
		duration_ms = greatest(
			0,
			floor(extract(epoch from (stale_after - started_at)) * 1000)::bigint
		),
		error_stage = coalesce(error_stage, 'unknown'),
		error_message = coalesce(error_message, '크롤링 실행이 제한 시간 안에 종료되지 않았습니다.')
	where status = 'running'
		and stale_after <= now();

	delete from public.crawl_runs
	where status <> 'running'
		and started_at < now() - interval '90 days';

	get diagnostics v_deleted_count = row_count;
	return v_deleted_count;
end;
$$;

revoke all on function public.begin_crawl_run(text, uuid, integer)
	from public, anon, authenticated;
revoke all on function public.finish_crawl_run(bigint, uuid, jsonb)
	from public, anon, authenticated;
revoke all on function public.get_crawl_runs_dashboard(integer, integer)
	from public, anon, service_role;
revoke all on function public.cleanup_crawl_runs()
	from public, anon, authenticated, service_role;

grant execute on function public.begin_crawl_run(text, uuid, integer) to service_role;
grant execute on function public.finish_crawl_run(bigint, uuid, jsonb) to service_role;
grant execute on function public.get_crawl_runs_dashboard(integer, integer) to authenticated;

do $$
declare
	v_job_id bigint;
begin
	for v_job_id in
		select jobid
		from cron.job
		where jobname = 'applemint-clean-crawl-runs'
	loop
		perform cron.unschedule(v_job_id);
	end loop;

	perform cron.schedule(
		'applemint-clean-crawl-runs',
		'15 18 * * *',
		'select public.cleanup_crawl_runs()'
	);
end;
$$;
