begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

create table public.web_push_subscriptions (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users (id) on delete cascade,
	endpoint text not null unique,
	p256dh text not null,
	auth text not null,
	expiration_time timestamp with time zone,
	active boolean not null default true,
	last_seen_at timestamp with time zone not null default now(),
	disabled_at timestamp with time zone,
	created_at timestamp with time zone not null default now(),
	updated_at timestamp with time zone not null default now(),
	constraint web_push_subscriptions_endpoint_check check (
		octet_length(endpoint) between 16 and 4096
		and endpoint ~ '^https://'
	),
	constraint web_push_subscriptions_p256dh_check check (
		octet_length(p256dh) between 32 and 512
		and p256dh ~ '^[A-Za-z0-9_-]+$'
	),
	constraint web_push_subscriptions_auth_check check (
		octet_length(auth) between 8 and 128
		and auth ~ '^[A-Za-z0-9_-]+$'
	),
	constraint web_push_subscriptions_disabled_check check (
		(active and disabled_at is null)
		or (not active and disabled_at is not null)
	)
);

create index web_push_subscriptions_active_idx
	on public.web_push_subscriptions (id)
	where active;
create index web_push_subscriptions_inactive_cleanup_idx
	on public.web_push_subscriptions (updated_at)
	where not active;

create table public.web_push_deliveries (
	id bigint generated by default as identity primary key,
	run_id bigint not null references public.crawl_runs (id) on delete cascade,
	subscription_id bigint not null
		references public.web_push_subscriptions (id) on delete cascade,
	source text not null,
	inserted_count integer not null,
	state text not null default 'pending',
	available_at timestamp with time zone not null default now(),
	lease_token uuid,
	lease_expires_at timestamp with time zone,
	attempt_count integer not null default 0,
	delivered_at timestamp with time zone,
	last_error_code text,
	created_at timestamp with time zone not null default now(),
	updated_at timestamp with time zone not null default now(),
	constraint web_push_deliveries_run_subscription_key
		unique (run_id, subscription_id),
	constraint web_push_deliveries_source_check
		check (source in ('arcalive', 'battlepage', 'insagirl')),
	constraint web_push_deliveries_count_check check (inserted_count > 0),
	constraint web_push_deliveries_state_check check (
		state in ('pending', 'processing', 'retry', 'delivered', 'dead', 'skipped')
	),
	constraint web_push_deliveries_attempt_check check (
		attempt_count between 0 and 6
	),
	constraint web_push_deliveries_lease_check check (
		(
			state = 'processing'
			and lease_token is not null
			and lease_expires_at is not null
		)
		or (
			state <> 'processing'
			and lease_token is null
			and lease_expires_at is null
		)
	),
	constraint web_push_deliveries_delivered_check check (
		(state = 'delivered' and delivered_at is not null)
		or (state <> 'delivered' and delivered_at is null)
	),
	constraint web_push_deliveries_error_code_check check (
		last_error_code is null
		or (
			octet_length(last_error_code) between 1 and 80
			and last_error_code ~ '^[a-z0-9-]+$'
		)
	)
);

create index web_push_deliveries_claim_idx
	on public.web_push_deliveries (available_at, id)
	where state in ('pending', 'retry');
create index web_push_deliveries_expired_lease_idx
	on public.web_push_deliveries (lease_expires_at, id)
	where state = 'processing';
create index web_push_deliveries_badge_idx
	on public.web_push_deliveries (subscription_id, created_at)
	where state <> 'skipped';
create index web_push_deliveries_cleanup_idx
	on public.web_push_deliveries (updated_at)
	where state in ('delivered', 'skipped', 'dead');

alter table public.web_push_subscriptions enable row level security;
alter table public.web_push_deliveries enable row level security;

revoke all on table public.web_push_subscriptions
	from public, anon, authenticated;
revoke all on table public.web_push_deliveries
	from public, anon, authenticated;
revoke all on sequence public.web_push_subscriptions_id_seq
	from public, anon, authenticated;
revoke all on sequence public.web_push_deliveries_id_seq
	from public, anon, authenticated;

grant all on table public.web_push_subscriptions to service_role;
grant all on table public.web_push_deliveries to service_role;
grant all on sequence public.web_push_subscriptions_id_seq to service_role;
grant all on sequence public.web_push_deliveries_id_seq to service_role;

create or replace function public.upsert_web_push_subscription(
	p_endpoint text,
	p_p256dh text,
	p_auth text,
	p_expiration_time timestamp with time zone default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_user_id uuid := auth.uid();
	v_now timestamp with time zone := now();
	v_subscription_id bigint;
begin
	if not public.is_applemint_owner() or v_user_id is null then
		raise exception using
			errcode = '42501',
			message = 'Only the Applemint owner can manage web push subscriptions.';
	end if;
	if p_endpoint is null
		or octet_length(p_endpoint) not between 16 and 4096
		or p_endpoint !~ '^https://'
		or p_p256dh is null
		or octet_length(p_p256dh) not between 32 and 512
		or p_p256dh !~ '^[A-Za-z0-9_-]+$'
		or p_auth is null
		or octet_length(p_auth) not between 8 and 128
		or p_auth !~ '^[A-Za-z0-9_-]+$'
	then
		raise exception using
			errcode = '22023',
			message = 'Invalid web push subscription.';
	end if;

	insert into public.web_push_subscriptions (
		user_id,
		endpoint,
		p256dh,
		auth,
		expiration_time,
		active,
		last_seen_at,
		disabled_at,
		updated_at
	)
	values (
		v_user_id,
		p_endpoint,
		p_p256dh,
		p_auth,
		p_expiration_time,
		true,
		v_now,
		null,
		v_now
	)
	on conflict (endpoint) do update
	set
		user_id = excluded.user_id,
		p256dh = excluded.p256dh,
		auth = excluded.auth,
		expiration_time = excluded.expiration_time,
		active = true,
		last_seen_at = v_now,
		disabled_at = null,
		updated_at = v_now
	returning id into v_subscription_id;

	update public.web_push_deliveries
	set
		state = 'skipped',
		lease_token = null,
		lease_expires_at = null,
		last_error_code = 'subscription-reactivated',
		updated_at = v_now
	where subscription_id = v_subscription_id
		and state in ('pending', 'retry', 'processing')
		and created_at <= v_now;

	return jsonb_build_object('active', true);
end;
$$;

create or replace function public.disable_web_push_subscription(
	p_endpoint text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_user_id uuid := auth.uid();
	v_now timestamp with time zone := now();
	v_subscription_id bigint;
begin
	if not public.is_applemint_owner() or v_user_id is null then
		raise exception using
			errcode = '42501',
			message = 'Only the Applemint owner can manage web push subscriptions.';
	end if;
	if p_endpoint is null or octet_length(p_endpoint) not between 16 and 4096 then
		raise exception using
			errcode = '22023',
			message = 'Invalid web push endpoint.';
	end if;

	update public.web_push_subscriptions
	set
		active = false,
		disabled_at = v_now,
		updated_at = v_now
	where user_id = v_user_id and endpoint = p_endpoint and active
	returning id into v_subscription_id;

	if v_subscription_id is not null then
		update public.web_push_deliveries
		set
			state = 'skipped',
			lease_token = null,
			lease_expires_at = null,
			last_error_code = 'subscription-disabled',
			updated_at = v_now
		where subscription_id = v_subscription_id
			and state in ('pending', 'retry', 'processing');
	end if;

	return jsonb_build_object('disabled', v_subscription_id is not null);
end;
$$;

create or replace function public.acknowledge_web_push_inbox(
	p_endpoint text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_user_id uuid := auth.uid();
	v_now timestamp with time zone := now();
	v_subscription_id bigint;
begin
	if not public.is_applemint_owner() or v_user_id is null then
		raise exception using
			errcode = '42501',
			message = 'Only the Applemint owner can acknowledge web push items.';
	end if;
	if p_endpoint is null or octet_length(p_endpoint) not between 16 and 4096 then
		raise exception using
			errcode = '22023',
			message = 'Invalid web push endpoint.';
	end if;

	update public.web_push_subscriptions
	set last_seen_at = v_now, updated_at = v_now
	where user_id = v_user_id and endpoint = p_endpoint and active
	returning id into v_subscription_id;

	if v_subscription_id is not null then
		update public.web_push_deliveries
		set
			state = 'skipped',
			lease_token = null,
			lease_expires_at = null,
			last_error_code = 'inbox-acknowledged',
			updated_at = v_now
		where subscription_id = v_subscription_id
			and state in ('pending', 'retry', 'processing')
			and created_at <= v_now;
	end if;

	return jsonb_build_object(
		'acknowledged',
		v_subscription_id is not null,
		'acknowledgedAt',
		case
			when v_subscription_id is null then null
			else v_now
		end
	);
end;
$$;

create or replace function public.claim_web_push_deliveries(
	p_limit integer default 20,
	p_lease_seconds integer default 120
)
returns table (
	delivery_id bigint,
	delivery_lease_token uuid,
	subscription_id bigint,
	endpoint text,
	p256dh text,
	auth text,
	expiration_time timestamp with time zone,
	run_id text,
	source text,
	inserted_count integer,
	badge_count bigint,
	created_at timestamp with time zone
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_now timestamp with time zone := now();
	v_lease_token uuid := gen_random_uuid();
begin
	if p_limit < 1 or p_limit > 20 then
		raise exception using
			errcode = '22023',
			message = 'Web push claim limit must be between 1 and 20.';
	end if;
	if p_lease_seconds < 30 or p_lease_seconds > 600 then
		raise exception using
			errcode = '22023',
			message = 'Web push lease must be between 30 and 600 seconds.';
	end if;

	update public.web_push_deliveries as delivery
	set
		state = case
			when delivery.created_at <= v_now - interval '24 hours'
				then 'dead'
			else 'retry'
		end,
		available_at = v_now,
		lease_token = null,
		lease_expires_at = null,
		last_error_code = case
			when delivery.created_at <= v_now - interval '24 hours'
				then 'delivery-expired'
			else 'lease-expired'
		end,
		updated_at = v_now
	where delivery.state = 'processing'
		and delivery.lease_expires_at <= v_now;

	update public.web_push_deliveries as delivery
	set
		state = 'dead',
		lease_token = null,
		lease_expires_at = null,
		last_error_code = 'delivery-expired',
		updated_at = v_now
	where delivery.state in ('pending', 'retry')
		and delivery.created_at <= v_now - interval '24 hours';

	return query
	with candidates as (
		select delivery.id
		from public.web_push_deliveries as delivery
		inner join public.web_push_subscriptions as subscription
			on subscription.id = delivery.subscription_id
		where delivery.state in ('pending', 'retry')
			and delivery.available_at <= v_now
			and delivery.created_at > v_now - interval '24 hours'
			and subscription.active
			and (
				subscription.expiration_time is null
				or subscription.expiration_time > v_now
			)
		order by delivery.available_at, delivery.id
		for update of delivery skip locked
		limit p_limit
	),
	claimed as (
		update public.web_push_deliveries as delivery
		set
			state = 'processing',
			lease_token = v_lease_token,
			lease_expires_at = v_now + make_interval(secs => p_lease_seconds),
			attempt_count = delivery.attempt_count + 1,
			updated_at = v_now
		from candidates
		where delivery.id = candidates.id
		returning delivery.*
	)
	select
		claimed.id,
		claimed.lease_token,
		subscription.id,
		subscription.endpoint,
		subscription.p256dh,
		subscription.auth,
		subscription.expiration_time,
		claimed.run_id::text,
		claimed.source,
		claimed.inserted_count,
		coalesce(badge.total, 0),
		claimed.created_at
	from claimed
	inner join public.web_push_subscriptions as subscription
		on subscription.id = claimed.subscription_id
	left join lateral (
		select sum(delivery.inserted_count)::bigint as total
		from public.web_push_deliveries as delivery
		where delivery.subscription_id = subscription.id
			and delivery.created_at > subscription.last_seen_at
			and delivery.state <> 'skipped'
	) as badge on true
	order by claimed.id;
end;
$$;

create or replace function public.complete_web_push_delivery(
	p_delivery_id bigint,
	p_lease_token uuid
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_updated boolean;
begin
	update public.web_push_deliveries
	set
		state = 'delivered',
		lease_token = null,
		lease_expires_at = null,
		delivered_at = now(),
		last_error_code = null,
		updated_at = now()
	where id = p_delivery_id
		and lease_token = p_lease_token
		and state = 'processing'
	returning true into v_updated;

	return coalesce(v_updated, false);
end;
$$;

create or replace function public.retry_web_push_delivery(
	p_delivery_id bigint,
	p_lease_token uuid,
	p_error_code text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_now timestamp with time zone := now();
	v_attempt_count integer;
	v_created_at timestamp with time zone;
	v_state text;
	v_delay interval;
begin
	if p_error_code is null
		or octet_length(p_error_code) not between 1 and 80
		or p_error_code !~ '^[a-z0-9-]+$'
	then
		raise exception using
			errcode = '22023',
			message = 'Invalid web push error code.';
	end if;

	select delivery.attempt_count, delivery.created_at
	into v_attempt_count, v_created_at
	from public.web_push_deliveries as delivery
	where delivery.id = p_delivery_id
		and delivery.lease_token = p_lease_token
		and delivery.state = 'processing'
	for update;

	if v_attempt_count is null then
		return jsonb_build_object('updated', false);
	end if;

	if v_attempt_count >= 6 or v_created_at <= v_now - interval '24 hours' then
		v_state := 'dead';
		v_delay := interval '0 seconds';
	else
		v_state := 'retry';
		v_delay := (array[
			interval '1 minute',
			interval '5 minutes',
			interval '30 minutes',
			interval '2 hours',
			interval '6 hours'
		])[v_attempt_count];
	end if;

	update public.web_push_deliveries
	set
		state = v_state,
		available_at = case
			when v_state = 'retry' then v_now + v_delay
			else available_at
		end,
		lease_token = null,
		lease_expires_at = null,
		last_error_code = p_error_code,
		updated_at = v_now
	where id = p_delivery_id
		and lease_token = p_lease_token
		and state = 'processing';

	return jsonb_build_object(
		'updated',
		true,
		'state',
		v_state,
		'availableAt',
		case when v_state = 'retry' then v_now + v_delay else null end
	);
end;
$$;

create or replace function public.invalidate_web_push_subscription(
	p_delivery_id bigint,
	p_lease_token uuid,
	p_error_code text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_now timestamp with time zone := now();
	v_subscription_id bigint;
	v_skipped_count integer := 0;
begin
	if p_error_code not in ('push-404', 'push-410') then
		raise exception using
			errcode = '22023',
			message = 'Unsupported web push invalidation code.';
	end if;

	update public.web_push_deliveries
	set
		state = 'dead',
		lease_token = null,
		lease_expires_at = null,
		last_error_code = p_error_code,
		updated_at = v_now
	where id = p_delivery_id
		and lease_token = p_lease_token
		and state = 'processing'
	returning subscription_id into v_subscription_id;

	if v_subscription_id is null then
		return jsonb_build_object('invalidated', false, 'skippedCount', 0);
	end if;

	update public.web_push_subscriptions
	set
		active = false,
		disabled_at = v_now,
		updated_at = v_now
	where id = v_subscription_id;

	update public.web_push_deliveries
	set
		state = 'skipped',
		lease_token = null,
		lease_expires_at = null,
		last_error_code = 'subscription-invalid',
		updated_at = v_now
	where subscription_id = v_subscription_id
		and id <> p_delivery_id
		and state in ('pending', 'retry', 'processing');
	get diagnostics v_skipped_count = row_count;

	return jsonb_build_object(
		'invalidated',
		true,
		'skippedCount',
		v_skipped_count
	);
end;
$$;

create or replace function public.cleanup_web_push_notifications()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_delivery_count integer;
	v_subscription_count integer;
begin
	delete from public.web_push_deliveries
	where state in ('delivered', 'skipped', 'dead')
		and updated_at < now() - interval '90 days';
	get diagnostics v_delivery_count = row_count;

	delete from public.web_push_subscriptions
	where not active
		and updated_at < now() - interval '90 days';
	get diagnostics v_subscription_count = row_count;

	return jsonb_build_object(
		'deliveryCount',
		v_delivery_count,
		'subscriptionCount',
		v_subscription_count
	);
end;
$$;

create or replace function public.dispatch_due_web_push_notifications()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_base_url text;
	v_internal_secret text;
	v_request_id bigint;
begin
	perform pg_catalog.pg_advisory_xact_lock(
		pg_catalog.hashtextextended('applemint:web-push-dispatch', 0)
	);

	if not exists (
		select 1
		from public.web_push_deliveries as delivery
		inner join public.web_push_subscriptions as subscription
			on subscription.id = delivery.subscription_id
		where subscription.active
			and (
				(
					delivery.state in ('pending', 'retry')
					and delivery.available_at <= now()
				)
				or (
					delivery.state = 'processing'
					and delivery.lease_expires_at <= now()
				)
			)
	) then
		return jsonb_build_object('status', 'idle');
	end if;

	select secret.decrypted_secret
	into v_base_url
	from vault.decrypted_secrets as secret
	where secret.name = 'crawl_app_base_url'
	order by secret.created_at desc
	limit 1;

	select secret.decrypted_secret
	into v_internal_secret
	from vault.decrypted_secrets as secret
	where secret.name = 'crawl_internal_secret'
	order by secret.created_at desc
	limit 1;

	v_base_url := rtrim(v_base_url, '/');
	if v_base_url is null
		or v_base_url !~ '^https?://[^[:space:]]+$'
		or v_internal_secret is null
		or octet_length(v_internal_secret) < 32
	then
		return jsonb_build_object('status', 'configuration-missing');
	end if;

	select net.http_post(
		url := v_base_url || '/api/push/dispatch',
		headers := jsonb_build_object(
			'Content-Type', 'application/json',
			'x-applemint-internal-secret', v_internal_secret
		),
		body := jsonb_build_object('limit', 20),
		timeout_milliseconds := 60000
	)
	into v_request_id;

	return jsonb_build_object('status', 'dispatched', 'requestId', v_request_id);
end;
$$;

create or replace function public.finish_crawl_run(
	p_run_id bigint,
	p_lock_token uuid,
	p_result jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_status text;
	v_warnings jsonb;
	v_failures jsonb;
	v_parser_observations jsonb;
	v_finished_at timestamp with time zone := now();
	v_duration_ms bigint;
	v_source text;
	v_run_trigger text;
	v_inserted_count integer;
begin
	if p_result is null or jsonb_typeof(p_result) <> 'object' then
		raise exception using errcode = '22023', message = 'Crawl run result must be a JSON object.';
	end if;
	v_status := p_result ->> 'status';
	if v_status not in ('succeeded', 'partial', 'failed') then
		raise exception using errcode = '22023', message = 'Unsupported terminal crawl run status.';
	end if;

	v_warnings := coalesce(p_result -> 'warnings', '[]'::jsonb);
	v_failures := coalesce(p_result -> 'failures', '[]'::jsonb);
	v_parser_observations := coalesce(p_result -> 'parserObservations', '[]'::jsonb);
	if jsonb_typeof(v_warnings) <> 'array'
		or jsonb_typeof(v_failures) <> 'array'
		or jsonb_typeof(v_parser_observations) <> 'array'
	then
		raise exception using errcode = '22023', message = 'Crawl run details must be JSON arrays.';
	end if;

	update public.crawl_runs
	set
		status = v_status,
		finished_at = v_finished_at,
		duration_ms = greatest(
			0,
			floor(extract(epoch from (v_finished_at - started_at)) * 1000)::bigint
		),
		retry_count = coalesce((p_result ->> 'retryCount')::integer, 0),
		recovered_count = coalesce((p_result ->> 'recoveredCount')::integer, 0),
		attempted_count = coalesce((p_result ->> 'attemptedCount')::integer, 0),
		succeeded_count = coalesce((p_result ->> 'succeededCount')::integer, 0),
		extracted_count = coalesce((p_result ->> 'extractedCount')::integer, 0),
		inserted_count = coalesce((p_result ->> 'insertedCount')::integer, 0),
		skipped_count = coalesce((p_result ->> 'skippedCount')::integer, 0),
		warning_count = coalesce((p_result ->> 'warningCount')::integer, 0),
		failure_count = coalesce((p_result ->> 'failureCount')::integer, 0),
		network_failure_count = coalesce((p_result ->> 'networkFailureCount')::integer, 0),
		parser_failure_count = coalesce((p_result ->> 'parserFailureCount')::integer, 0),
		timeout_failure_count = coalesce((p_result ->> 'timeoutFailureCount')::integer, 0),
		parser_valid_count = coalesce((p_result ->> 'parserValidCount')::integer, 0),
		parser_minimum_count = coalesce((p_result ->> 'parserMinimumCount')::integer, 0),
		warnings = v_warnings,
		failures = v_failures,
		parser_observations = v_parser_observations,
		error_stage = nullif(p_result ->> 'errorStage', ''),
		error_message = nullif(p_result ->> 'errorMessage', '')
	where id = p_run_id
		and lock_token = p_lock_token
		and status = 'running'
	returning duration_ms, source, run_trigger, inserted_count
	into v_duration_ms, v_source, v_run_trigger, v_inserted_count;

	if v_duration_ms is null then
		raise exception using errcode = 'P0002', message = 'Running crawl run was not found.';
	end if;

	if v_run_trigger = 'scheduled'
		and v_status in ('succeeded', 'partial')
		and v_inserted_count > 0
	then
		insert into public.web_push_deliveries (
			run_id,
			subscription_id,
			source,
			inserted_count
		)
		select
			p_run_id,
			subscription.id,
			v_source,
			v_inserted_count
		from public.web_push_subscriptions as subscription
		where subscription.active
			and (
				subscription.expiration_time is null
				or subscription.expiration_time > v_finished_at
			)
		on conflict (run_id, subscription_id) do nothing;
	end if;

	delete from public.crawl_run_locks
	where lock_token = p_lock_token
		and lock_key in ('global-crawl', 'crawl:' || v_source);

	return jsonb_build_object(
		'runId', p_run_id::text,
		'status', v_status,
		'durationMs', v_duration_ms
	);
end;
$$;

revoke all on function public.upsert_web_push_subscription(
	text, text, text, timestamp with time zone
) from public, anon, authenticated, service_role;
revoke all on function public.disable_web_push_subscription(text)
	from public, anon, authenticated, service_role;
revoke all on function public.acknowledge_web_push_inbox(text)
	from public, anon, authenticated, service_role;
grant execute on function public.upsert_web_push_subscription(
	text, text, text, timestamp with time zone
) to authenticated;
grant execute on function public.disable_web_push_subscription(text)
	to authenticated;
grant execute on function public.acknowledge_web_push_inbox(text)
	to authenticated;

revoke all on function public.claim_web_push_deliveries(integer, integer)
	from public, anon, authenticated, service_role;
revoke all on function public.complete_web_push_delivery(bigint, uuid)
	from public, anon, authenticated, service_role;
revoke all on function public.retry_web_push_delivery(bigint, uuid, text)
	from public, anon, authenticated, service_role;
revoke all on function public.invalidate_web_push_subscription(bigint, uuid, text)
	from public, anon, authenticated, service_role;
revoke all on function public.cleanup_web_push_notifications()
	from public, anon, authenticated, service_role;
revoke all on function public.dispatch_due_web_push_notifications()
	from public, anon, authenticated, service_role;

grant execute on function public.claim_web_push_deliveries(integer, integer)
	to service_role;
grant execute on function public.complete_web_push_delivery(bigint, uuid)
	to service_role;
grant execute on function public.retry_web_push_delivery(bigint, uuid, text)
	to service_role;
grant execute on function public.invalidate_web_push_subscription(bigint, uuid, text)
	to service_role;
grant execute on function public.cleanup_web_push_notifications()
	to service_role;
grant execute on function public.dispatch_due_web_push_notifications()
	to service_role;

do $$
declare
	v_job_id bigint;
begin
	for v_job_id in
		select jobid
		from cron.job
		where jobname in (
			'applemint-dispatch-web-push',
			'applemint-clean-web-push'
		)
	loop
		perform cron.unschedule(v_job_id);
	end loop;

	perform cron.schedule(
		'applemint-dispatch-web-push',
		'*/5 * * * *',
		'select public.dispatch_due_web_push_notifications()'
	);
	perform cron.schedule(
		'applemint-clean-web-push',
		'20 18 * * *',
		'select public.cleanup_web_push_notifications()'
	);
end;
$$;

commit;
