create table public.crawl_alert_settings (
	id boolean primary key default true,
	parser_failure_streak integer not null default 2,
	parser_drop_ratio numeric(5, 4) not null default 0.5,
	parser_drop_streak integer not null default 2,
	no_success_seconds integer not null default 172800,
	transport_window integer not null default 3,
	transport_error_ratio numeric(5, 4) not null default 0.5,
	transport_min_failures integer not null default 2,
	cooldown_seconds integer not null default 86400,
	last_evaluated_at timestamp with time zone,
	constraint crawl_alert_settings_singleton_check check (id),
	constraint crawl_alert_settings_positive_check check (
		parser_failure_streak between 1 and 10
		and parser_drop_ratio > 0 and parser_drop_ratio <= 1
		and parser_drop_streak between 1 and 10
		and no_success_seconds between 3600 and 2592000
		and transport_window between 1 and 20
		and transport_error_ratio > 0 and transport_error_ratio <= 1
		and transport_min_failures between 1 and 100
		and cooldown_seconds between 3600 and 604800
	)
);

insert into public.crawl_alert_settings (id) values (true);

create table public.crawl_alert_incidents (
	id bigint generated by default as identity primary key,
	source text not null,
	status text not null default 'open',
	active_signals text[] not null,
	opened_at timestamp with time zone not null,
	last_observed_at timestamp with time zone not null,
	recovered_at timestamp with time zone,
	last_notification_at timestamp with time zone,
	github_issue_number bigint,
	github_issue_url text,
	snapshot jsonb not null default '{}'::jsonb,
	constraint crawl_alert_incidents_source_check
		check (source in ('arcalive', 'battlepage', 'insagirl', 'issuelink')),
	constraint crawl_alert_incidents_status_check check (status in ('open', 'recovered')),
	constraint crawl_alert_incidents_signal_check check (
		active_signals <@ array[
			'parser-failure',
			'parser-volume-drop',
			'no-recent-success',
			'transport-error-rate'
		]::text[]
		and array_length(active_signals, 1) is not null
		and cardinality(active_signals) <= 4
	),
	constraint crawl_alert_incidents_time_check check (
		(status = 'open' and recovered_at is null)
		or (status = 'recovered' and recovered_at is not null)
	),
	constraint crawl_alert_incidents_snapshot_check check (jsonb_typeof(snapshot) = 'object'),
	constraint crawl_alert_incidents_github_check check (
		(github_issue_number is null and github_issue_url is null)
		or (github_issue_number > 0 and github_issue_url ~ '^https://github[.]com/[^/]+/[^/]+/issues/[0-9]+$')
	)
);

create unique index crawl_alert_incidents_open_source_idx
	on public.crawl_alert_incidents (source)
	where status = 'open';
create index crawl_alert_incidents_opened_at_idx
	on public.crawl_alert_incidents (opened_at desc, id desc);

create table public.crawl_alert_notifications (
	id bigint generated by default as identity primary key,
	incident_id bigint not null references public.crawl_alert_incidents(id) on delete cascade,
	event text not null,
	payload jsonb not null,
	created_at timestamp with time zone not null default now(),
	delivered_at timestamp with time zone,
	delivery_attempt_count integer not null default 0,
	last_error text,
	constraint crawl_alert_notifications_event_check
		check (event in ('opened', 'updated', 'reminder', 'recovered')),
	constraint crawl_alert_notifications_payload_check check (jsonb_typeof(payload) = 'object'),
	constraint crawl_alert_notifications_attempt_check check (delivery_attempt_count >= 0)
);

create unique index crawl_alert_notifications_pending_event_idx
	on public.crawl_alert_notifications (incident_id, event)
	where delivered_at is null;
create index crawl_alert_notifications_pending_idx
	on public.crawl_alert_notifications (created_at, id)
	where delivered_at is null;

alter table public.crawl_alert_settings enable row level security;
alter table public.crawl_alert_incidents enable row level security;
alter table public.crawl_alert_notifications enable row level security;

revoke all on table public.crawl_alert_settings from public, anon, authenticated;
revoke all on table public.crawl_alert_incidents from public, anon, authenticated;
revoke all on table public.crawl_alert_notifications from public, anon, authenticated;
revoke all on sequence public.crawl_alert_incidents_id_seq from public, anon, authenticated;
revoke all on sequence public.crawl_alert_notifications_id_seq from public, anon, authenticated;

grant all on table public.crawl_alert_settings to service_role;
grant all on table public.crawl_alert_incidents to service_role;
grant all on table public.crawl_alert_notifications to service_role;
grant all on sequence public.crawl_alert_incidents_id_seq to service_role;
grant all on sequence public.crawl_alert_notifications_id_seq to service_role;

create or replace function public.evaluate_crawl_alerts(
	p_now timestamp with time zone default now()
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_settings public.crawl_alert_settings%rowtype;
	v_source text;
	v_incident public.crawl_alert_incidents%rowtype;
	v_signals text[];
	v_previous_signals text[];
	v_snapshot jsonb;
	v_latest_run_id bigint;
	v_parser_failure_trigger boolean;
	v_latest_parser_clean boolean;
	v_parser_drop_trigger boolean;
	v_latest_parser_ratio numeric;
	v_first_run_at timestamp with time zone;
	v_last_success_at timestamp with time zone;
	v_transport_trigger boolean;
	v_transport_recovered boolean;
	v_transport_attempted bigint;
	v_transport_failures bigint;
	v_transport_ratio numeric;
	v_incident_id bigint;
	v_open_count integer;
	v_pending_count integer;
begin
	if p_now is null then
		raise exception using errcode = '22023', message = 'Evaluation time is required.';
	end if;

	select * into strict v_settings
	from public.crawl_alert_settings
	where id = true
	for update;

	update public.crawl_runs
	set
		status = 'interrupted',
		finished_at = stale_after,
		duration_ms = greatest(0, floor(extract(epoch from (stale_after - started_at)) * 1000)::bigint),
		error_stage = coalesce(error_stage, 'unknown'),
		error_message = coalesce(error_message, '크롤링 실행이 제한 시간 안에 종료되지 않았습니다.')
	where status = 'running' and stale_after <= p_now;

	for v_source in
		select source from (values
			('arcalive'::text), ('battlepage'), ('insagirl'), ('issuelink')
		) as sources(source)
	loop
		select * into v_incident
		from public.crawl_alert_incidents
		where source = v_source and status = 'open'
		for update;
		v_previous_signals := coalesce(v_incident.active_signals, array[]::text[]);

		select run.id into v_latest_run_id
		from public.crawl_runs as run
		where run.source = v_source and run.status <> 'running'
		order by run.started_at desc, run.id desc
		limit 1;

		select coalesce(
			count(*) = v_settings.parser_failure_streak
			and bool_and(recent.parser_failure_count > 0),
			false
		)
		into v_parser_failure_trigger
		from (
			select run.parser_failure_count
			from public.crawl_runs as run
			where run.source = v_source
				and run.status <> 'running'
				and run.attempted_count > 0
			order by run.started_at desc, run.id desc
			limit v_settings.parser_failure_streak
		) as recent;

		select coalesce(run.parser_failure_count = 0, false)
		into v_latest_parser_clean
		from public.crawl_runs as run
		where run.source = v_source
			and run.status <> 'running'
			and run.attempted_count > 0
		order by run.started_at desc, run.id desc
		limit 1;
		v_latest_parser_clean := coalesce(v_latest_parser_clean, false);

		select coalesce(
			count(*) = v_settings.parser_drop_streak
			and bool_and(recent.ratio < v_settings.parser_drop_ratio),
			false
		)
		into v_parser_drop_trigger
		from (
			select run.parser_valid_count::numeric / run.parser_minimum_count as ratio
			from public.crawl_runs as run
			where run.source = v_source
				and run.status <> 'running'
				and run.parser_minimum_count > 0
			order by run.started_at desc, run.id desc
			limit v_settings.parser_drop_streak
		) as recent;

		select run.parser_valid_count::numeric / run.parser_minimum_count
		into v_latest_parser_ratio
		from public.crawl_runs as run
		where run.source = v_source
			and run.status <> 'running'
			and run.parser_minimum_count > 0
		order by run.started_at desc, run.id desc
		limit 1;

		select min(run.started_at), max(run.finished_at) filter (
			where run.status in ('succeeded', 'partial')
		)
		into v_first_run_at, v_last_success_at
		from public.crawl_runs as run
		where run.source = v_source and run.status <> 'running';

		select
			coalesce(sum(recent.attempted_count), 0),
			coalesce(sum(recent.transport_failures), 0),
			coalesce(
				sum(recent.transport_failures)::numeric / nullif(sum(recent.attempted_count), 0),
				0
			),
			coalesce(
				count(*) = v_settings.transport_window
				and sum(recent.transport_failures) >= v_settings.transport_min_failures
				and sum(recent.transport_failures)::numeric / nullif(sum(recent.attempted_count), 0)
					>= v_settings.transport_error_ratio,
				false
			)
		into v_transport_attempted, v_transport_failures, v_transport_ratio, v_transport_trigger
		from (
			select
				run.attempted_count,
				run.network_failure_count + run.timeout_failure_count as transport_failures
			from public.crawl_runs as run
			where run.source = v_source
				and run.status <> 'running'
				and run.attempted_count > 0
			order by run.started_at desc, run.id desc
			limit v_settings.transport_window
		) as recent;

		select coalesce(count(*) = 2 and bool_and(recent.transport_failures = 0), false)
		into v_transport_recovered
		from (
			select run.network_failure_count + run.timeout_failure_count as transport_failures
			from public.crawl_runs as run
			where run.source = v_source
				and run.status <> 'running'
				and run.attempted_count > 0
			order by run.started_at desc, run.id desc
			limit 2
		) as recent;

		v_signals := array[]::text[];
		if (
			'parser-failure' = any(v_previous_signals) and not v_latest_parser_clean
		) or (
			not ('parser-failure' = any(v_previous_signals)) and v_parser_failure_trigger
		) then
			v_signals := array_append(v_signals, 'parser-failure');
		end if;
		if (
			'parser-volume-drop' = any(v_previous_signals)
			and coalesce(v_latest_parser_ratio, 0) < 1
		) or (
			not ('parser-volume-drop' = any(v_previous_signals)) and v_parser_drop_trigger
		) then
			v_signals := array_append(v_signals, 'parser-volume-drop');
		end if;
		if v_first_run_at is not null
			and coalesce(v_last_success_at, v_first_run_at)
				<= p_now - make_interval(secs => v_settings.no_success_seconds)
		then
			v_signals := array_append(v_signals, 'no-recent-success');
		end if;
		if (
			'transport-error-rate' = any(v_previous_signals) and not v_transport_recovered
		) or (
			not ('transport-error-rate' = any(v_previous_signals)) and v_transport_trigger
		) then
			v_signals := array_append(v_signals, 'transport-error-rate');
		end if;

		v_snapshot := jsonb_build_object(
			'latestRunId', case when v_latest_run_id is null then null else v_latest_run_id::text end,
			'parserFailureTriggered', v_parser_failure_trigger,
			'parserValidRatio', v_latest_parser_ratio,
			'lastSuccessAt', v_last_success_at,
			'hoursSinceSuccess', case
				when coalesce(v_last_success_at, v_first_run_at) is null then null
				else round((extract(epoch from (p_now - coalesce(v_last_success_at, v_first_run_at))) / 3600)::numeric, 2)
			end,
			'transportWindow', v_settings.transport_window,
			'transportAttemptedCount', v_transport_attempted,
			'transportFailureCount', v_transport_failures,
			'transportFailureRatio', round(v_transport_ratio, 4)
		);

		if v_incident.id is null and cardinality(v_signals) > 0 then
			insert into public.crawl_alert_incidents (
				source, active_signals, opened_at, last_observed_at, snapshot
			)
			values (v_source, v_signals, p_now, p_now, v_snapshot)
			returning id into v_incident_id;

			insert into public.crawl_alert_notifications (incident_id, event, payload, created_at)
			values (
				v_incident_id,
				'opened',
				jsonb_build_object('source', v_source, 'signals', v_signals, 'snapshot', v_snapshot, 'observedAt', p_now),
				p_now
			);
		elsif v_incident.id is not null and cardinality(v_signals) = 0 then
			update public.crawl_alert_incidents
			set
				status = 'recovered',
				active_signals = v_previous_signals,
				last_observed_at = p_now,
				recovered_at = p_now,
				snapshot = v_snapshot
			where id = v_incident.id;

			insert into public.crawl_alert_notifications (incident_id, event, payload, created_at)
			values (
				v_incident.id,
				'recovered',
				jsonb_build_object('source', v_source, 'signals', v_previous_signals, 'snapshot', v_snapshot, 'observedAt', p_now),
				p_now
			)
			on conflict (incident_id, event) where delivered_at is null do update
			set payload = excluded.payload, created_at = excluded.created_at;
		elsif v_incident.id is not null then
			update public.crawl_alert_incidents
			set active_signals = v_signals, last_observed_at = p_now, snapshot = v_snapshot
			where id = v_incident.id;

			if v_signals is distinct from v_previous_signals then
				update public.crawl_alert_notifications
				set payload = jsonb_build_object(
					'source', v_source,
					'signals', v_signals,
					'snapshot', v_snapshot,
					'observedAt', p_now
				), created_at = p_now
				where incident_id = v_incident.id and event = 'opened' and delivered_at is null;

				if not found then
					insert into public.crawl_alert_notifications (incident_id, event, payload, created_at)
					values (
						v_incident.id,
						'updated',
						jsonb_build_object('source', v_source, 'signals', v_signals, 'snapshot', v_snapshot, 'observedAt', p_now),
						p_now
					)
					on conflict (incident_id, event) where delivered_at is null do update
					set payload = excluded.payload, created_at = excluded.created_at;
				end if;
			elsif v_incident.last_notification_at is not null
				and v_incident.last_notification_at <= p_now - make_interval(secs => v_settings.cooldown_seconds)
			then
				insert into public.crawl_alert_notifications (incident_id, event, payload, created_at)
				values (
					v_incident.id,
					'reminder',
					jsonb_build_object('source', v_source, 'signals', v_signals, 'snapshot', v_snapshot, 'observedAt', p_now),
					p_now
				)
				on conflict (incident_id, event) where delivered_at is null do nothing;
			end if;
		end if;
	end loop;

	update public.crawl_alert_settings set last_evaluated_at = p_now where id = true;
	select count(*) into v_open_count from public.crawl_alert_incidents where status = 'open';
	select count(*) into v_pending_count from public.crawl_alert_notifications where delivered_at is null;

	return jsonb_build_object(
		'evaluatedAt', p_now,
		'activeIncidentCount', v_open_count,
		'pendingNotificationCount', v_pending_count
	);
end;
$$;

create or replace function public.get_pending_crawl_alert_notifications(
	p_limit integer default 20
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
	v_result jsonb;
begin
	if p_limit < 1 or p_limit > 100 then
		raise exception using errcode = '22023', message = 'Notification limit must be between 1 and 100.';
	end if;

	select coalesce(jsonb_agg(
		jsonb_build_object(
			'id', notification.id::text,
			'incidentId', notification.incident_id::text,
			'event', notification.event,
			'payload', notification.payload,
			'createdAt', notification.created_at,
			'githubIssueNumber', incident.github_issue_number,
			'githubIssueUrl', incident.github_issue_url
		)
		order by notification.created_at, notification.id
	), '[]'::jsonb)
	into v_result
	from (
		select * from public.crawl_alert_notifications
		where delivered_at is null
		order by created_at, id
		limit p_limit
	) as notification
	inner join public.crawl_alert_incidents as incident on incident.id = notification.incident_id;

	return v_result;
end;
$$;

create or replace function public.complete_crawl_alert_notification(
	p_notification_id bigint,
	p_github_issue_number bigint,
	p_github_issue_url text
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_incident_id bigint;
begin
	if p_github_issue_number is null or p_github_issue_number <= 0
		or p_github_issue_url !~ '^https://github[.]com/[^/]+/[^/]+/issues/[0-9]+$'
	then
		raise exception using errcode = '22023', message = 'A valid GitHub issue is required.';
	end if;

	update public.crawl_alert_notifications
	set delivered_at = now(), delivery_attempt_count = delivery_attempt_count + 1, last_error = null
	where id = p_notification_id and delivered_at is null
	returning incident_id into v_incident_id;

	if v_incident_id is null then
		return false;
	end if;

	update public.crawl_alert_incidents
	set
		last_notification_at = now(),
		github_issue_number = p_github_issue_number,
		github_issue_url = p_github_issue_url
	where id = v_incident_id;

	return true;
end;
$$;

create or replace function public.fail_crawl_alert_notification(
	p_notification_id bigint,
	p_error_code text
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_updated boolean;
begin
	if p_error_code is null or p_error_code !~ '^[a-z0-9_-]{1,64}$' then
		raise exception using errcode = '22023', message = 'A safe delivery error code is required.';
	end if;

	update public.crawl_alert_notifications
	set delivery_attempt_count = delivery_attempt_count + 1, last_error = p_error_code
	where id = p_notification_id and delivered_at is null
	returning true into v_updated;

	return coalesce(v_updated, false);
end;
$$;

create or replace function public.get_crawl_alerts_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
	v_result jsonb;
begin
	if not public.is_applemint_owner() then
		raise exception using
			errcode = '42501',
			message = 'Only the Applemint owner can read crawl alerts.';
	end if;

	select jsonb_build_object(
		'alerts', coalesce((
			select jsonb_agg(jsonb_build_object(
				'id', incident.id::text,
				'source', incident.source,
				'activeSignals', incident.active_signals,
				'openedAt', incident.opened_at,
				'lastObservedAt', incident.last_observed_at,
				'lastNotificationAt', incident.last_notification_at,
				'githubIssueNumber', incident.github_issue_number,
				'githubIssueUrl', incident.github_issue_url,
				'snapshot', incident.snapshot
			) order by incident.opened_at desc, incident.id desc)
			from public.crawl_alert_incidents as incident
			where incident.status = 'open'
		), '[]'::jsonb),
		'alertSettings', jsonb_build_object(
			'parserFailureStreak', settings.parser_failure_streak,
			'parserDropRatio', settings.parser_drop_ratio,
			'parserDropStreak', settings.parser_drop_streak,
			'noSuccessSeconds', settings.no_success_seconds,
			'transportWindow', settings.transport_window,
			'transportErrorRatio', settings.transport_error_ratio,
			'transportMinFailures', settings.transport_min_failures,
			'cooldownSeconds', settings.cooldown_seconds,
			'lastEvaluatedAt', settings.last_evaluated_at
		)
	)
	into v_result
	from public.crawl_alert_settings as settings
	where settings.id = true;

	return v_result;
end;
$$;

create or replace function public.cleanup_crawl_runs()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_deleted_count bigint;
begin
	update public.crawl_runs
	set
		status = 'interrupted',
		finished_at = stale_after,
		duration_ms = greatest(0, floor(extract(epoch from (stale_after - started_at)) * 1000)::bigint),
		error_stage = coalesce(error_stage, 'unknown'),
		error_message = coalesce(error_message, '크롤링 실행이 제한 시간 안에 종료되지 않았습니다.')
	where status = 'running' and stale_after <= now();

	delete from public.crawl_alert_notifications
	where delivered_at is not null and created_at < now() - interval '90 days';

	delete from public.crawl_alert_incidents
	where status = 'recovered' and recovered_at < now() - interval '90 days';

	delete from public.crawl_runs
	where status <> 'running' and started_at < now() - interval '90 days';

	get diagnostics v_deleted_count = row_count;
	return v_deleted_count;
end;
$$;

revoke all on function public.evaluate_crawl_alerts(timestamp with time zone)
	from public, anon, authenticated;
revoke all on function public.get_pending_crawl_alert_notifications(integer)
	from public, anon, authenticated;
revoke all on function public.complete_crawl_alert_notification(bigint, bigint, text)
	from public, anon, authenticated;
revoke all on function public.fail_crawl_alert_notification(bigint, text)
	from public, anon, authenticated;
revoke all on function public.get_crawl_alerts_dashboard()
	from public, anon, service_role;

grant execute on function public.evaluate_crawl_alerts(timestamp with time zone) to service_role;
grant execute on function public.get_pending_crawl_alert_notifications(integer) to service_role;
grant execute on function public.complete_crawl_alert_notification(bigint, bigint, text) to service_role;
grant execute on function public.fail_crawl_alert_notification(bigint, text) to service_role;
grant execute on function public.get_crawl_alerts_dashboard() to authenticated;
