begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

lock table public."new-threads", public."quick-save", public.trash
	in share row exclusive mode;

do $$
begin
	if exists (
		select legacy.id
		from (
			select id from public."new-threads"
			union all
			select id from public."quick-save"
			union all
			select id from public.trash
		) as legacy
		group by legacy.id
		having count(*) > 1
	) then
		raise exception using
			errcode = '23505',
			message = 'Legacy thread IDs overlap across tables. The threads migration was not applied.';
	end if;
end;
$$;

create table public.threads (
	id bigint generated by default as identity primary key,
	created_at timestamp with time zone not null default now(),
	type text,
	url text,
	title text,
	description text,
	host text,
	tag text[],
	state text not null default 'inbox',
	captured_at timestamp with time zone not null default now(),
	state_changed_at timestamp with time zone not null default now(),
	constraint threads_state_check check (state in ('inbox', 'saved', 'trash')),
	constraint threads_no_removed_media_types check (type not in ('media', 'youtube'))
);

comment on table public.threads is
	'Applemint thread source of truth. Legacy thread tables are synchronized projections during rollout.';
comment on column public.threads.created_at is
	'Logical thread creation time. It never changes when the thread state changes.';
comment on column public.threads.captured_at is
	'Time when the thread was first captured from its source. It is immutable across state changes.';
comment on column public.threads.state_changed_at is
	'Time when the thread entered its current state.';

insert into public.threads (
	id,
	created_at,
	type,
	url,
	title,
	description,
	host,
	tag,
	state,
	captured_at,
	state_changed_at
)
select
	thread.id,
	thread.captured_at,
	thread.type,
	thread.url,
	thread.title,
	thread.description,
	thread.host,
	thread.tag,
	'inbox',
	thread.captured_at,
	thread.created_at
from public."new-threads" as thread
union all
select
	thread.id,
	thread.captured_at,
	thread.type,
	thread.url,
	thread.title,
	thread.description,
	thread.host,
	thread.tag,
	'saved',
	thread.captured_at,
	thread.created_at
from public."quick-save" as thread
union all
select
	thread.id,
	thread.captured_at,
	thread.type,
	thread.url,
	thread.title,
	thread.description,
	thread.host,
	thread.tag,
	'trash',
	thread.captured_at,
	thread.created_at
from public.trash as thread;

do $$
declare
	v_max_id bigint;
	v_legacy_count bigint;
	v_thread_count bigint;
	v_mismatch_count bigint;
begin
	select max(id) into v_max_id from public.threads;
	if v_max_id is null then
		perform setval(pg_get_serial_sequence('public.threads', 'id'), 1, false);
	else
		perform setval(pg_get_serial_sequence('public.threads', 'id'), v_max_id, true);
	end if;

	select
		(select count(*) from public."new-threads")
		+ (select count(*) from public."quick-save")
		+ (select count(*) from public.trash)
	into v_legacy_count;
	select count(*) into v_thread_count from public.threads;

	with legacy as (
		select id, captured_at as created_at, type, url, title, description, host, tag,
			'inbox'::text as state, captured_at, created_at as state_changed_at
		from public."new-threads"
		union all
		select id, captured_at, type, url, title, description, host, tag,
			'saved', captured_at, created_at
		from public."quick-save"
		union all
		select id, captured_at, type, url, title, description, host, tag,
			'trash', captured_at, created_at
		from public.trash
	)
	select count(*)
	into v_mismatch_count
	from legacy
	full join public.threads as thread using (id)
	where legacy.id is null
		or thread.id is null
		or row(
			legacy.created_at,
			legacy.type,
			legacy.url,
			legacy.title,
			legacy.description,
			legacy.host,
			legacy.tag,
			legacy.state,
			legacy.captured_at,
			legacy.state_changed_at
		) is distinct from row(
			thread.created_at,
			thread.type,
			thread.url,
			thread.title,
			thread.description,
			thread.host,
			thread.tag,
			thread.state,
			thread.captured_at,
			thread.state_changed_at
		);

	if v_legacy_count <> v_thread_count or v_mismatch_count <> 0 then
		raise exception using
			errcode = 'P0001',
			message = format(
				'Thread backfill verification failed: legacy=%s threads=%s mismatches=%s.',
				v_legacy_count,
				v_thread_count,
				v_mismatch_count
			);
	end if;
end;
$$;

create index idx_threads_state_changed_at_id
	on public.threads (state, state_changed_at desc, id desc);

create index idx_threads_state_type_changed_at_id
	on public.threads (state, type, state_changed_at desc, id desc);

alter table public.threads enable row level security;

create policy "Applemint owner can read threads"
	on public.threads
	for select
	to authenticated
	using ((select public.is_applemint_owner()));

revoke all on table public.threads from public, anon, authenticated, service_role;
grant select on table public.threads to authenticated;
grant select, insert, update, delete on table public.threads to service_role;

revoke all on sequence public.threads_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.threads_id_seq to service_role;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated, service_role;

create function private.set_thread_state_changed_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
	if new.state is distinct from old.state then
		new.state_changed_at := statement_timestamp();
	end if;
	return new;
end;
$$;

revoke all on function private.set_thread_state_changed_at()
	from public, anon, authenticated, service_role;

create trigger set_thread_state_changed_at
before update of state on public.threads
for each row
execute function private.set_thread_state_changed_at();

create function private.sync_thread_legacy_projection()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_thread public.threads;
begin
	if tg_op = 'DELETE' then
		delete from public."new-threads" where id = old.id;
		delete from public."quick-save" where id = old.id;
		delete from public.trash where id = old.id;
		return old;
	end if;

	v_thread := new;
	delete from public."new-threads" where id = v_thread.id;
	delete from public."quick-save" where id = v_thread.id;
	delete from public.trash where id = v_thread.id;

	if v_thread.state = 'inbox' then
		insert into public."new-threads" (
			id, created_at, type, url, title, description, host, tag, captured_at
		) values (
			v_thread.id, v_thread.state_changed_at, v_thread.type, v_thread.url,
			v_thread.title, v_thread.description, v_thread.host, v_thread.tag,
			v_thread.captured_at
		);
	elsif v_thread.state = 'saved' then
		insert into public."quick-save" (
			id, created_at, type, url, title, description, host, tag, captured_at
		) values (
			v_thread.id, v_thread.state_changed_at, v_thread.type, v_thread.url,
			v_thread.title, v_thread.description, v_thread.host, v_thread.tag,
			v_thread.captured_at
		);
	else
		insert into public.trash (
			id, created_at, type, url, title, description, host, tag, captured_at
		) values (
			v_thread.id, v_thread.state_changed_at, v_thread.type, v_thread.url,
			v_thread.title, v_thread.description, v_thread.host, v_thread.tag,
			v_thread.captured_at
		);
	end if;

	return new;
end;
$$;

revoke all on function private.sync_thread_legacy_projection()
	from public, anon, authenticated, service_role;

create trigger sync_thread_legacy_projection
after insert or update or delete on public.threads
for each row
execute function private.sync_thread_legacy_projection();

revoke insert, update, delete, truncate, references, trigger
	on public."new-threads", public."quick-save", public.trash
	from service_role;
grant select on public."new-threads", public."quick-save", public.trash to service_role;
revoke usage, update on sequence
	public."new-threads_id_seq", public."quick-save_id_seq", public.trash_id_seq
	from service_role;

create function public.list_threads_page(
	p_state text,
	p_limit integer default 24,
	p_cursor_state_changed_at timestamp with time zone default null,
	p_cursor_id bigint default null,
	p_filter_type text default null
)
returns table (
	id bigint,
	created_at timestamp with time zone,
	type text,
	url text,
	title text,
	description text,
	host text,
	tag text[],
	state text,
	captured_at timestamp with time zone,
	state_changed_at timestamp with time zone
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
	if not public.is_applemint_owner() then
		raise exception using errcode = '42501', message = 'Only the Applemint owner can list threads.';
	end if;
	if p_state is null or p_state not in ('inbox', 'saved', 'trash') then
		raise exception using errcode = '22023', message = format('Unsupported thread state: %s', p_state);
	end if;
	if p_limit is null or p_limit < 1 or p_limit > 100 then
		raise exception using errcode = '22023', message = 'Thread page limit must be between 1 and 100.';
	end if;
	if (p_cursor_state_changed_at is null) <> (p_cursor_id is null) then
		raise exception using errcode = '22023', message = 'Both cursor fields must be provided together.';
	end if;
	if p_cursor_id is not null and p_cursor_id <= 0 then
		raise exception using errcode = '22023', message = 'Thread cursor id must be positive.';
	end if;

	return query
	select
		thread.id,
		thread.created_at,
		thread.type,
		thread.url,
		thread.title,
		thread.description,
		thread.host,
		thread.tag,
		thread.state,
		thread.captured_at,
		thread.state_changed_at
	from public.threads as thread
	where thread.state = p_state
		and (
			p_cursor_state_changed_at is null
			or (thread.state_changed_at, thread.id) < (p_cursor_state_changed_at, p_cursor_id)
		)
		and (p_filter_type is null or thread.type = p_filter_type)
	order by thread.state_changed_at desc, thread.id desc
	limit (p_limit + 1);
end;
$$;

revoke all on function public.list_threads_page(text, integer, timestamp with time zone, bigint, text)
	from public, anon, authenticated, service_role;
grant execute on function public.list_threads_page(text, integer, timestamp with time zone, bigint, text)
	to authenticated;

create function public.get_thread_stats(
	p_state text,
	p_filter_type text default null
)
returns table (key text, label text, count bigint, total_count bigint)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
	if not public.is_applemint_owner() then
		raise exception using errcode = '42501', message = 'Only the Applemint owner can read thread statistics.';
	end if;
	if p_state is null or p_state not in ('inbox', 'saved', 'trash') then
		raise exception using errcode = '22023', message = format('Unsupported thread state: %s', p_state);
	end if;

	return query
	with filtered_rows as (
		select thread.type
		from public.threads as thread
		where thread.state = p_state
			and (p_filter_type is null or thread.type = p_filter_type)
	),
	grouped_rows as (
		select filtered_rows.type as stat_key, filtered_rows.type as stat_label,
			count(*)::bigint as stat_count
		from filtered_rows
		group by filtered_rows.type
	),
	total_rows as (
		select count(*)::bigint as stat_total_count from filtered_rows
	)
	select grouped_rows.stat_key, grouped_rows.stat_label, grouped_rows.stat_count,
		total_rows.stat_total_count
	from grouped_rows
	cross join total_rows
	order by grouped_rows.stat_count desc;
end;
$$;

revoke all on function public.get_thread_stats(text, text)
	from public, anon, authenticated, service_role;
grant execute on function public.get_thread_stats(text, text) to authenticated;

create function public.transition_thread_state(
	p_thread_id bigint,
	p_expected_state text,
	p_destination_state text
)
returns public.threads
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_thread public.threads;
begin
	if not public.is_applemint_owner() then
		raise exception using errcode = '42501', message = 'Only the Applemint owner can move a thread.';
	end if;
	if p_thread_id is null or p_thread_id <= 0 then
		raise exception using errcode = '22023', message = 'Thread ID must be positive.';
	end if;
	if (p_expected_state, p_destination_state) not in (
		('inbox', 'saved'),
		('inbox', 'trash'),
		('saved', 'trash'),
		('trash', 'inbox')
	) then
		raise exception using
			errcode = '22023',
			message = format(
				'Unsupported thread transition: %s -> %s',
				p_expected_state,
				p_destination_state
			);
	end if;

	update public.threads
	set state = p_destination_state
	where id = p_thread_id and state = p_expected_state
	returning * into v_thread;

	if found then
		return v_thread;
	end if;

	select * into v_thread from public.threads where id = p_thread_id;
	if not found then
		raise exception using
			errcode = 'P0002',
			message = format('Thread %s was not found.', p_thread_id);
	end if;
	if v_thread.state = p_destination_state then
		return v_thread;
	end if;

	raise exception using
		errcode = '40001',
		message = format(
			'Thread %s is in state %s instead of expected state %s.',
			p_thread_id,
			v_thread.state,
			p_expected_state
		);
end;
$$;

revoke all on function public.transition_thread_state(bigint, text, text)
	from public, anon, authenticated, service_role;
grant execute on function public.transition_thread_state(bigint, text, text) to authenticated;

create function public.bulk_move_inbox_to_trash()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
	v_moved_count bigint;
begin
	if not public.is_applemint_owner() then
		raise exception using errcode = '42501', message = 'Only the Applemint owner can move threads.';
	end if;

	with moved as (
		update public.threads
		set state = 'trash'
		where state = 'inbox'
		returning 1
	)
	select count(*) into v_moved_count from moved;

	return v_moved_count;
end;
$$;

revoke all on function public.bulk_move_inbox_to_trash()
	from public, anon, authenticated, service_role;
grant execute on function public.bulk_move_inbox_to_trash() to authenticated;

create or replace function public.move_thread(
	p_thread_id bigint,
	p_source text,
	p_destination text
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_source_state text;
	v_destination_state text;
	v_thread public.threads;
begin
	v_source_state := case p_source
		when 'new-threads' then 'inbox'
		when 'quick-save' then 'saved'
		when 'trash' then 'trash'
		else null
	end;
	v_destination_state := case p_destination
		when 'new-threads' then 'inbox'
		when 'quick-save' then 'saved'
		when 'trash' then 'trash'
		else null
	end;

	if v_source_state is null or v_destination_state is null then
		raise exception using
			errcode = '22023',
			message = format('Unsupported thread transition: %s -> %s', p_source, p_destination);
	end if;

	v_thread := public.transition_thread_state(
		p_thread_id,
		v_source_state,
		v_destination_state
	);
	return v_thread.id;
end;
$$;

revoke all on function public.move_thread(bigint, text, text)
	from public, anon, service_role;
grant execute on function public.move_thread(bigint, text, text) to authenticated;

create or replace function public.bulk_move_new_threads_to_trash()
returns bigint
language sql
security invoker
set search_path = ''
as $$
	select public.bulk_move_inbox_to_trash();
$$;

revoke all on function public.bulk_move_new_threads_to_trash()
	from public, anon, service_role;
grant execute on function public.bulk_move_new_threads_to_trash() to authenticated;

create or replace function public.list_thread_page(
	p_list text,
	p_limit integer default 24,
	p_cursor_created_at timestamp with time zone default null,
	p_cursor_id bigint default null,
	p_filter_type text default null
)
returns table (
	id bigint,
	created_at timestamp with time zone,
	type text,
	url text,
	title text,
	description text,
	host text,
	tag text[],
	captured_at timestamp with time zone
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
	v_state text;
begin
	v_state := case p_list
		when 'new-threads' then 'inbox'
		when 'quick-save' then 'saved'
		when 'trash' then 'trash'
		else null
	end;
	if v_state is null then
		raise exception using errcode = '22023', message = format('Unsupported thread list: %s', p_list);
	end if;

	return query
	select
		page.id,
		page.state_changed_at as created_at,
		page.type,
		page.url,
		page.title,
		page.description,
		page.host,
		page.tag,
		page.captured_at
	from public.list_threads_page(
		v_state,
		p_limit,
		p_cursor_created_at,
		p_cursor_id,
		p_filter_type
	) as page;
end;
$$;

revoke all on function public.list_thread_page(text, integer, timestamp with time zone, bigint, text)
	from public, anon, service_role;
grant execute on function public.list_thread_page(text, integer, timestamp with time zone, bigint, text)
	to authenticated;

create or replace function public.get_new_threads_stats(in_filter_type text default null)
returns table (key text, label text, count bigint, total_count bigint)
language sql
stable
security invoker
set search_path = ''
as $$
	select stats.key, stats.label, stats.count, stats.total_count
	from public.get_thread_stats('inbox', in_filter_type) as stats;
$$;

revoke all on function public.get_new_threads_stats(text)
	from public, anon, service_role;
grant execute on function public.get_new_threads_stats(text) to authenticated;

create or replace function public.clean_trash()
returns void
language sql
security invoker
set search_path = ''
as $$
	delete from public.threads
	where state = 'trash'
		and state_changed_at < now() - interval '7 days';
$$;

revoke all on function public.clean_trash() from public, anon, authenticated;
grant execute on function public.clean_trash() to service_role;

create or replace function public.ingest_crawl_items(
	p_crawl_source text,
	p_items jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
	v_result jsonb;
begin
	if p_crawl_source not in ('arcalive', 'battlepage', 'insagirl') then
		raise exception using errcode = '22023', message = 'Unsupported crawl source.';
	end if;
	if p_items is null or jsonb_typeof(p_items) <> 'array' then
		raise exception using errcode = '22023', message = 'Crawl items must be a JSON array.';
	end if;
	if jsonb_array_length(p_items) > 1000 then
		raise exception using errcode = '22023', message = 'A crawl batch cannot exceed 1000 items.';
	end if;

	with normalized_payload as materialized (
		select distinct on (btrim(item ->> 'url'))
			btrim(item ->> 'url') as url,
			nullif(item ->> 'title', '') as title,
			nullif(item ->> 'description', '') as description,
			nullif(item ->> 'host', '') as host,
			case
				when coalesce(nullif(item ->> 'type', ''), 'normal') in ('media', 'youtube')
					then 'normal'
				else coalesce(nullif(item ->> 'type', ''), 'normal')
			end as type,
			case
				when jsonb_typeof(item -> 'tag') = 'array' then
					array(select jsonb_array_elements_text(item -> 'tag'))
				else null
			end as tag
		from jsonb_array_elements(p_items) as payload(item)
		where nullif(btrim(item ->> 'url'), '') is not null
		order by btrim(item ->> 'url')
	),
	claimed as (
		insert into public."crawl-history" (url, crawl_source, host)
		select url, p_crawl_source, host
		from normalized_payload
		on conflict (crawl_source, url) do nothing
		returning url
	),
	inserted as (
		insert into public.threads (url, title, description, host, type, tag, state)
		select payload.url, payload.title, payload.description, payload.host,
			payload.type, payload.tag, 'inbox'
		from normalized_payload as payload
		inner join claimed using (url)
		returning url
	),
	counts as (
		select
			(select count(*) from normalized_payload) as input_count,
			(select count(*) from inserted) as inserted_count
	)
	select jsonb_build_object(
		'insertedCount', inserted_count,
		'skippedCount', input_count - inserted_count
	)
	into v_result
	from counts;

	return coalesce(v_result, jsonb_build_object('insertedCount', 0, 'skippedCount', 0));
end;
$$;

revoke all on function public.ingest_crawl_items(text, jsonb)
	from public, anon, authenticated;
grant execute on function public.ingest_crawl_items(text, jsonb) to service_role;

create function public.get_thread_storage_consistency()
returns table (
	state text,
	canonical_count bigint,
	legacy_count bigint,
	mismatch_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
	with legacy as (
		select id, captured_at as created_at, type, url, title, description, host, tag,
			'inbox'::text as state, captured_at, created_at as state_changed_at
		from public."new-threads"
		union all
		select id, captured_at, type, url, title, description, host, tag,
			'saved', captured_at, created_at
		from public."quick-save"
		union all
		select id, captured_at, type, url, title, description, host, tag,
			'trash', captured_at, created_at
		from public.trash
	),
	states(state) as (
		values ('inbox'::text), ('saved'::text), ('trash'::text)
	)
	select
		states.state,
		(select count(*) from public.threads where threads.state = states.state),
		(select count(*) from legacy where legacy.state = states.state),
		(
			select count(*)
			from public.threads as thread
			full join legacy on legacy.id = thread.id
			where coalesce(thread.state, legacy.state) = states.state
				and (
					thread.id is null
					or legacy.id is null
					or row(
						thread.created_at, thread.type, thread.url, thread.title,
						thread.description, thread.host, thread.tag, thread.state,
						thread.captured_at, thread.state_changed_at
					) is distinct from row(
						legacy.created_at, legacy.type, legacy.url, legacy.title,
						legacy.description, legacy.host, legacy.tag, legacy.state,
						legacy.captured_at, legacy.state_changed_at
					)
				)
		)
	from states
	order by states.state;
$$;

revoke all on function public.get_thread_storage_consistency()
	from public, anon, authenticated, service_role;
grant execute on function public.get_thread_storage_consistency() to service_role;

commit;
