

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."clean_trash"() RETURNS "void"
    LANGUAGE "sql"
    SET "search_path" TO ''
    AS $$
    DELETE FROM public.trash 
    WHERE created_at < NOW() - INTERVAL '7 days';
$$;


CREATE OR REPLACE FUNCTION "public"."get_new_threads_stats"("in_scope" "text" DEFAULT 'normal'::"text", "in_filter_type" "text" DEFAULT NULL::"text", "in_issuelink_category" "text" DEFAULT NULL::"text") RETURNS TABLE("key" "text", "label" "text", "count" bigint, "total_count" bigint)
    LANGUAGE "sql" STABLE
    AS $$
	with filtered_rows as (
		select type, tag
		from public."new-threads"
		where
			(
				in_scope <> 'normal'
				or (type <> 'media' and type <> 'youtube')
			)
			and (
				in_filter_type is null
				or (
					in_filter_type = 'issuelink'
					and type = 'issuelink'
					and (
						in_issuelink_category is null
						or tag[2] = in_issuelink_category
					)
				)
				or (
					in_filter_type <> 'issuelink'
					and type = in_filter_type
				)
			)
	),
	grouped_rows as (
		select
			case
				when type = 'issuelink' then 'issuelink::' || coalesce(tag[2], 'unknown')
				else type
			end as key,
			case
				when type = 'issuelink' then coalesce(tag[2], 'unknown')
				else type
			end as label,
			count(*)::bigint as count
		from filtered_rows
		group by 1, 2
	),
	total_rows as (
		select count(*)::bigint as total_count
		from filtered_rows
	)
	select grouped_rows.key, grouped_rows.label, grouped_rows.count, total_rows.total_count
	from grouped_rows
	cross join total_rows
	order by grouped_rows.count desc;
$$;


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."crawl-history" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "url" "text",
    "crawl_source" "text",
    "host" "text"
);


ALTER TABLE "public"."crawl-history" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."crawl-history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."filter-keyword" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" "text",
    "method" "text"
);


ALTER TABLE "public"."filter-keyword" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."filter-keyword_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."new-threads" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "url" "text",
    "title" "text",
    "description" "text",
    "host" "text",
    "sub_url" "text"[],
    "tag" "text"[]
);


ALTER TABLE "public"."new-threads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."new-threads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."quick-save" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "url" "text",
    "title" "text",
    "description" "text",
    "host" "text"
);


ALTER TABLE "public"."quick-save" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quick-save_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trash" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "url" "text",
    "title" "text",
    "description" "text",
    "host" "text"
);


ALTER TABLE "public"."trash" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trash_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."crawl-history"
    ADD CONSTRAINT "crawl-history_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."filter-keyword"
    ADD CONSTRAINT "filter-keyword_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."new-threads"
    ADD CONSTRAINT "new-threads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quick-save"
    ADD CONSTRAINT "quick-save_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trash"
    ADD CONSTRAINT "trash_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "idx_crawl_history_source_url_unique" ON "public"."crawl-history" USING "btree" ("crawl_source", "url");



CREATE INDEX "idx_new_threads_created_at_id" ON "public"."new-threads" USING "btree" ("created_at" DESC, "id" DESC);



CREATE INDEX "idx_new_threads_issuelink_category" ON "public"."new-threads" USING "btree" (("tag"[2])) WHERE ("type" = 'issuelink'::"text");



CREATE INDEX "idx_new_threads_type" ON "public"."new-threads" USING "btree" ("type");



CREATE POLICY "Enable delete for authenticated users only" ON "public"."new-threads" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable delete for authenticated users only" ON "public"."quick-save" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable delete for authenticated users only" ON "public"."trash" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable insert for anon users only" ON "public"."crawl-history" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Enable insert for anon users only" ON "public"."new-threads" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."new-threads" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."quick-save" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."trash" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."crawl-history" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."filter-keyword" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."new-threads" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."quick-save" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."trash" FOR SELECT USING (true);



ALTER TABLE "public"."crawl-history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."filter-keyword" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."new-threads" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."quick-save" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trash" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."clean_trash"() TO "anon";
GRANT ALL ON FUNCTION "public"."clean_trash"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."clean_trash"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_new_threads_stats"("in_scope" "text", "in_filter_type" "text", "in_issuelink_category" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_new_threads_stats"("in_scope" "text", "in_filter_type" "text", "in_issuelink_category" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_new_threads_stats"("in_scope" "text", "in_filter_type" "text", "in_issuelink_category" "text") TO "service_role";



GRANT ALL ON TABLE "public"."crawl-history" TO "anon";
GRANT ALL ON TABLE "public"."crawl-history" TO "authenticated";
GRANT ALL ON TABLE "public"."crawl-history" TO "service_role";



GRANT ALL ON SEQUENCE "public"."crawl-history_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."crawl-history_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."crawl-history_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."filter-keyword" TO "anon";
GRANT ALL ON TABLE "public"."filter-keyword" TO "authenticated";
GRANT ALL ON TABLE "public"."filter-keyword" TO "service_role";



GRANT ALL ON SEQUENCE "public"."filter-keyword_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."filter-keyword_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."filter-keyword_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."new-threads" TO "anon";
GRANT ALL ON TABLE "public"."new-threads" TO "authenticated";
GRANT ALL ON TABLE "public"."new-threads" TO "service_role";



GRANT ALL ON SEQUENCE "public"."new-threads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."new-threads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."new-threads_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."quick-save" TO "anon";
GRANT ALL ON TABLE "public"."quick-save" TO "authenticated";
GRANT ALL ON TABLE "public"."quick-save" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quick-save_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quick-save_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quick-save_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trash" TO "anon";
GRANT ALL ON TABLE "public"."trash" TO "authenticated";
GRANT ALL ON TABLE "public"."trash" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trash_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trash_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trash_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";





